

nameSuffix: -dev1
namespace: dev1

resources:

helmGlobals:
  chartHome: ./charts
patches:
- path: ./backend/patch.yaml
  target:
    kind: Deployment
    name: backend
- path: ./frontend/patch.yaml
  target:
    kind: Deployment
    name: frontend

